var searchData=
[
  ['receipt',['Receipt',['../classReceipt.html',1,'']]],
  ['receipt_5fnew',['Receipt_new',['../classReceipt__new.html',1,'']]],
  ['receipt_5ftlv',['RECEIPT_TLV',['../structFiscal__store_1_1RECEIPT__TLV.html',1,'Fiscal_store']]],
  ['receiptsdb',['ReceiptsDb',['../classReceiptsDb.html',1,'']]],
  ['reg_5fmask',['REG_MASK',['../structREG__MASK.html',1,'']]],
  ['req_5fdata_5fstruct',['req_data_struct',['../structFiscal__store_1_1req__data__struct.html',1,'Fiscal_store']]],
  ['req_5fname',['REQ_NAME',['../classRequisites_1_1REQ__NAME.html',1,'Requisites']]],
  ['request',['REQUEST',['../structJSON_1_1JSON__SEARCH__PRODUCT_1_1REQUEST.html',1,'JSON::JSON_SEARCH_PRODUCT::REQUEST'],['../structJSON_1_1JSON__CASH__INFO__REPORT_1_1REQUEST.html',1,'JSON::JSON_CASH_INFO_REPORT::REQUEST'],['../structJSON_1_1JSON__MONEY__DOCUMENT__REPORT_1_1REQUEST.html',1,'JSON::JSON_MONEY_DOCUMENT_REPORT::REQUEST'],['../structJSON_1_1JSON__COUNTERS__REPORT_1_1REQUEST.html',1,'JSON::JSON_COUNTERS_REPORT::REQUEST'],['../structJSON_1_1JSON__UNREGISTER_1_1REQUEST.html',1,'JSON::JSON_UNREGISTER::REQUEST'],['../structJSON_1_1JSON__SHIFT__DOCUMENT__REPORT_1_1REQUEST.html',1,'JSON::JSON_SHIFT_DOCUMENT_REPORT::REQUEST'],['../structJSON_1_1JSON__REGISTER_1_1REQUEST.html',1,'JSON::JSON_REGISTER::REQUEST'],['../structJSON_1_1JSON__HANDSHAKE_1_1REQUEST.html',1,'JSON::JSON_HANDSHAKE::REQUEST'],['../structJSON_1_1JSON__POLL___1_1REQUEST.html',1,'JSON::JSON_POLL_::REQUEST'],['../structJSON_1_1JSON__PURCHASE__DOCUMENT__REPORT_1_1REQUEST.html',1,'JSON::JSON_PURCHASE_DOCUMENT_REPORT::REQUEST'],['../structJSON_1_1JSON__KKT__REGISTER__INFO_1_1REQUEST.html',1,'JSON::JSON_KKT_REGISTER_INFO::REQUEST']]],
  ['requisite',['Requisite',['../classRequisites_1_1Requisite.html',1,'Requisites']]],
  ['requisites',['requisites',['../structReceipt_1_1requisites.html',1,'Receipt::requisites'],['../classRequisites.html',1,'Requisites']]],
  ['response',['RESPONSE',['../structJSON_1_1JSON__SHIFT__DOCUMENT__REPORT_1_1RESPONSE.html',1,'JSON::JSON_SHIFT_DOCUMENT_REPORT::RESPONSE'],['../structJSON_1_1JSON__COUNTERS__REPORT_1_1RESPONSE.html',1,'JSON::JSON_COUNTERS_REPORT::RESPONSE'],['../structJSON_1_1JSON__REGISTER_1_1RESPONSE.html',1,'JSON::JSON_REGISTER::RESPONSE'],['../structJSON_1_1JSON__HANDSHAKE_1_1RESPONSE.html',1,'JSON::JSON_HANDSHAKE::RESPONSE'],['../structJSON_1_1JSON__SEARCH__PRODUCT_1_1RESPONSE.html',1,'JSON::JSON_SEARCH_PRODUCT::RESPONSE'],['../structJSON_1_1JSON__UNREGISTER_1_1RESPONSE.html',1,'JSON::JSON_UNREGISTER::RESPONSE'],['../structJSON_1_1JSON__KKT__REGISTER__INFO_1_1RESPONSE.html',1,'JSON::JSON_KKT_REGISTER_INFO::RESPONSE'],['../structJSON_1_1JSON__PURCHASE__DOCUMENT__REPORT_1_1RESPONSE.html',1,'JSON::JSON_PURCHASE_DOCUMENT_REPORT::RESPONSE'],['../structJSON_1_1JSON__CASH__INFO__REPORT_1_1RESPONSE.html',1,'JSON::JSON_CASH_INFO_REPORT::RESPONSE'],['../structJSON_1_1JSON__POLL___1_1RESPONSE.html',1,'JSON::JSON_POLL_::RESPONSE'],['../structJSON_1_1JSON__MONEY__DOCUMENT__REPORT_1_1RESPONSE.html',1,'JSON::JSON_MONEY_DOCUMENT_REPORT::RESPONSE']]]
];
